- alias: 'Tidstest'
  trigger:
    - platform: time
      at: '12:45:00'

  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: switch.turn_on
      entity_id: switch.telldus_tzwp100_plugin_switch_switch
